import { Inter } from 'next/font/google'
import './globals.css'
import Home from '@/Components/Home/Home'
import Footer from '@/Components/Footer/Footer'
import Banner from '@/Components/Banner/Banner'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
  <div className="max-w-screen-xl mx-auto">
        <Home />
        <Banner/>
      <body className={inter.className}>{children}</body>
      <Footer />
      </div>
    </html>
  )
}
